public class Adress {
    public void homeAdress(){
        String yourName = 'Serhan';
        system.debug('My name is '+ yourName);
        integer memOfFamily= 5;
        system.debug('My member of family is ' + memOfFamily);
        integer houseNum=5918;
        system.debug('My house number is ' + houseNum);
        string streetName='Watersdown way';
        system.debug('Street name is ' + streetName);
        string cityName='Flowery Branch';
        system.debug('my city name is '+ cityName);
        string stateName='GA';
        system.debug('my state name is'+ stateName);
        string isoCode='432';
        system.debug('Iso code is '+ isoCode);
        string countryName='Usa';
        system.debug('Country name is'+ countryName);
        string countryIsoCode='5678rtgh';
        system.debug('my country iso code is '+ countryIsoCode);
        integer zipCode=30542;
        system.debug('My zip code is '+ zipCode);
        Boolean isThisYourCurrentHome=true;
        system.debug('Is this your current home '+ isThisYourCurrentHome);



  }
  
 
}
