public class PrimitiveDataTypeDemo2 {
    public void41  print1 (){
        Id id1 = '00B8Z00000AR';
        system.debug('print id=' + id1);
//Object --> object is a parent classto all primitive data types,subjects,custom classes and everything in apex
        Object obj1 = 'This is a strin';
        Object obj2 = 15;
        object obj3 = true

        system.debug('obj1 =' + obj1);
        system.debug('obj2 =' + obj2);
        system.debug('obj3 =' + obj3);
    
    }
}